package org.ccsds.moims.mo.mps;

import org.ccsds.moims.mo.mal.AreaElementFactory;
import org.ccsds.moims.mo.mal.structures.Element;
import org.ccsds.moims.mo.mps.structures.ActivityDefinition;
import org.ccsds.moims.mo.mps.structures.ActivityDefinitionList;
import org.ccsds.moims.mo.mps.structures.ActivityInstance;
import org.ccsds.moims.mo.mps.structures.ActivityInstanceList;
import org.ccsds.moims.mo.mps.structures.ActivityNode;
import org.ccsds.moims.mo.mps.structures.ActivityNodeList;
import org.ccsds.moims.mo.mps.structures.ActivityStatusEnum;
import org.ccsds.moims.mo.mps.structures.ActivityStatusEnumList;
import org.ccsds.moims.mo.mps.structures.ActivitySuspensionStatus;
import org.ccsds.moims.mo.mps.structures.ActivitySuspensionStatusList;
import org.ccsds.moims.mo.mps.structures.ActivityUpdate;
import org.ccsds.moims.mo.mps.structures.ActivityUpdateList;
import org.ccsds.moims.mo.mps.structures.Angle;
import org.ccsds.moims.mo.mps.structures.AngleConstraint;
import org.ccsds.moims.mo.mps.structures.AngleConstraintList;
import org.ccsds.moims.mo.mps.structures.AngleList;
import org.ccsds.moims.mo.mps.structures.AngleRepetition;
import org.ccsds.moims.mo.mps.structures.AngleRepetitionList;
import org.ccsds.moims.mo.mps.structures.AngleTrigger;
import org.ccsds.moims.mo.mps.structures.AngleTriggerList;
import org.ccsds.moims.mo.mps.structures.AngularVelocity;
import org.ccsds.moims.mo.mps.structures.AngularVelocityList;
import org.ccsds.moims.mo.mps.structures.ArgDef;
import org.ccsds.moims.mo.mps.structures.ArgDefList;
import org.ccsds.moims.mo.mps.structures.ArgSpec;
import org.ccsds.moims.mo.mps.structures.ArgSpecList;
import org.ccsds.moims.mo.mps.structures.ArgTypeEnum;
import org.ccsds.moims.mo.mps.structures.ArgTypeEnumList;
import org.ccsds.moims.mo.mps.structures.Argument;
import org.ccsds.moims.mo.mps.structures.ArgumentConstraint;
import org.ccsds.moims.mo.mps.structures.ArgumentConstraintList;
import org.ccsds.moims.mo.mps.structures.ArgumentList;
import org.ccsds.moims.mo.mps.structures.CartesianDirection;
import org.ccsds.moims.mo.mps.structures.CartesianDirectionList;
import org.ccsds.moims.mo.mps.structures.CartesianPosition;
import org.ccsds.moims.mo.mps.structures.CartesianPositionList;
import org.ccsds.moims.mo.mps.structures.ComplexEffect;
import org.ccsds.moims.mo.mps.structures.ComplexEffectList;
import org.ccsds.moims.mo.mps.structures.ComplexResourceConstraint;
import org.ccsds.moims.mo.mps.structures.ComplexResourceConstraintList;
import org.ccsds.moims.mo.mps.structures.ConstraintExpression;
import org.ccsds.moims.mo.mps.structures.ConstraintExpressionList;
import org.ccsds.moims.mo.mps.structures.ConstraintNode;
import org.ccsds.moims.mo.mps.structures.ConstraintNodeList;
import org.ccsds.moims.mo.mps.structures.DefListEntry;
import org.ccsds.moims.mo.mps.structures.DefListEntryList;
import org.ccsds.moims.mo.mps.structures.DirectionReference;
import org.ccsds.moims.mo.mps.structures.DirectionReferenceList;
import org.ccsds.moims.mo.mps.structures.DirectionRepetition;
import org.ccsds.moims.mo.mps.structures.DirectionRepetitionList;
import org.ccsds.moims.mo.mps.structures.DirectionTrigger;
import org.ccsds.moims.mo.mps.structures.DirectionTriggerList;
import org.ccsds.moims.mo.mps.structures.Distance;
import org.ccsds.moims.mo.mps.structures.DistanceConstraint;
import org.ccsds.moims.mo.mps.structures.DistanceConstraintList;
import org.ccsds.moims.mo.mps.structures.DistanceList;
import org.ccsds.moims.mo.mps.structures.DurationConstraint;
import org.ccsds.moims.mo.mps.structures.DurationConstraintList;
import org.ccsds.moims.mo.mps.structures.EffectOperationEnum;
import org.ccsds.moims.mo.mps.structures.EffectOperationEnumList;
import org.ccsds.moims.mo.mps.structures.EllipsoidalPositionConstraint;
import org.ccsds.moims.mo.mps.structures.EllipsoidalPositionConstraintList;
import org.ccsds.moims.mo.mps.structures.EventDefinition;
import org.ccsds.moims.mo.mps.structures.EventDefinitionList;
import org.ccsds.moims.mo.mps.structures.EventInstance;
import org.ccsds.moims.mo.mps.structures.EventInstanceList;
import org.ccsds.moims.mo.mps.structures.EventRepetition;
import org.ccsds.moims.mo.mps.structures.EventRepetitionList;
import org.ccsds.moims.mo.mps.structures.EventStatusEnum;
import org.ccsds.moims.mo.mps.structures.EventStatusEnumList;
import org.ccsds.moims.mo.mps.structures.EventTrigger;
import org.ccsds.moims.mo.mps.structures.EventTriggerList;
import org.ccsds.moims.mo.mps.structures.EventUpdate;
import org.ccsds.moims.mo.mps.structures.EventUpdateList;
import org.ccsds.moims.mo.mps.structures.EventWindow;
import org.ccsds.moims.mo.mps.structures.EventWindowList;
import org.ccsds.moims.mo.mps.structures.ExpressionOperatorEnum;
import org.ccsds.moims.mo.mps.structures.ExpressionOperatorEnumList;
import org.ccsds.moims.mo.mps.structures.ExternalExpression;
import org.ccsds.moims.mo.mps.structures.ExternalExpressionList;
import org.ccsds.moims.mo.mps.structures.FunctionConstraint;
import org.ccsds.moims.mo.mps.structures.FunctionConstraintList;
import org.ccsds.moims.mo.mps.structures.FunctionDefinitionDetails;
import org.ccsds.moims.mo.mps.structures.FunctionDefinitionDetailsList;
import org.ccsds.moims.mo.mps.structures.FunctionDetails;
import org.ccsds.moims.mo.mps.structures.FunctionDetailsList;
import org.ccsds.moims.mo.mps.structures.InsertedActivityDetails;
import org.ccsds.moims.mo.mps.structures.InsertedActivityDetailsList;
import org.ccsds.moims.mo.mps.structures.InsertedEventDetails;
import org.ccsds.moims.mo.mps.structures.InsertedEventDetailsList;
import org.ccsds.moims.mo.mps.structures.InterpolationTypeEnum;
import org.ccsds.moims.mo.mps.structures.InterpolationTypeEnumList;
import org.ccsds.moims.mo.mps.structures.ItemRevision;
import org.ccsds.moims.mo.mps.structures.ItemRevisionList;
import org.ccsds.moims.mo.mps.structures.LogicOpEnum;
import org.ccsds.moims.mo.mps.structures.LogicOpEnumList;
import org.ccsds.moims.mo.mps.structures.NamedElement;
import org.ccsds.moims.mo.mps.structures.NamedElementList;
import org.ccsds.moims.mo.mps.structures.NamedTargetDirection;
import org.ccsds.moims.mo.mps.structures.NamedTargetDirectionList;
import org.ccsds.moims.mo.mps.structures.NumericRange;
import org.ccsds.moims.mo.mps.structures.NumericRangeList;
import org.ccsds.moims.mo.mps.structures.NumericResource;
import org.ccsds.moims.mo.mps.structures.NumericResourceList;
import org.ccsds.moims.mo.mps.structures.ObjectPosition;
import org.ccsds.moims.mo.mps.structures.ObjectPositionList;
import org.ccsds.moims.mo.mps.structures.OrbitFilePosition;
import org.ccsds.moims.mo.mps.structures.OrbitFilePositionList;
import org.ccsds.moims.mo.mps.structures.OrbitRepetition;
import org.ccsds.moims.mo.mps.structures.OrbitRepetitionList;
import org.ccsds.moims.mo.mps.structures.OrbitalPosition;
import org.ccsds.moims.mo.mps.structures.OrbitalPositionList;
import org.ccsds.moims.mo.mps.structures.PartialPlan;
import org.ccsds.moims.mo.mps.structures.PartialPlanFilter;
import org.ccsds.moims.mo.mps.structures.PartialPlanFilterList;
import org.ccsds.moims.mo.mps.structures.PartialPlanList;
import org.ccsds.moims.mo.mps.structures.Plan;
import org.ccsds.moims.mo.mps.structures.PlanActivationStatus;
import org.ccsds.moims.mo.mps.structures.PlanActivationStatusList;
import org.ccsds.moims.mo.mps.structures.PlanFilter;
import org.ccsds.moims.mo.mps.structures.PlanFilterList;
import org.ccsds.moims.mo.mps.structures.PlanInformation;
import org.ccsds.moims.mo.mps.structures.PlanInformationList;
import org.ccsds.moims.mo.mps.structures.PlanList;
import org.ccsds.moims.mo.mps.structures.PlanQuery;
import org.ccsds.moims.mo.mps.structures.PlanQueryList;
import org.ccsds.moims.mo.mps.structures.PlanRevision;
import org.ccsds.moims.mo.mps.structures.PlanRevisionList;
import org.ccsds.moims.mo.mps.structures.PlanStatusEnum;
import org.ccsds.moims.mo.mps.structures.PlanStatusEnumList;
import org.ccsds.moims.mo.mps.structures.PlanSummaryStatus;
import org.ccsds.moims.mo.mps.structures.PlanSummaryStatusList;
import org.ccsds.moims.mo.mps.structures.PlanUpdate;
import org.ccsds.moims.mo.mps.structures.PlanUpdateList;
import org.ccsds.moims.mo.mps.structures.PlannedItems;
import org.ccsds.moims.mo.mps.structures.PlannedItemsList;
import org.ccsds.moims.mo.mps.structures.PlanningRequestDetails;
import org.ccsds.moims.mo.mps.structures.PlanningRequestDetailsList;
import org.ccsds.moims.mo.mps.structures.PlanningRequestResponse;
import org.ccsds.moims.mo.mps.structures.PlanningRequestResponseList;
import org.ccsds.moims.mo.mps.structures.PlanningUser;
import org.ccsds.moims.mo.mps.structures.PlanningUserList;
import org.ccsds.moims.mo.mps.structures.PointingConstraint;
import org.ccsds.moims.mo.mps.structures.PointingConstraintList;
import org.ccsds.moims.mo.mps.structures.PositionConstraint;
import org.ccsds.moims.mo.mps.structures.PositionConstraintList;
import org.ccsds.moims.mo.mps.structures.PositionReference;
import org.ccsds.moims.mo.mps.structures.PositionReferenceList;
import org.ccsds.moims.mo.mps.structures.PositionRepetition;
import org.ccsds.moims.mo.mps.structures.PositionRepetitionList;
import org.ccsds.moims.mo.mps.structures.PositionTrigger;
import org.ccsds.moims.mo.mps.structures.PositionTriggerList;
import org.ccsds.moims.mo.mps.structures.PredictabilityEnum;
import org.ccsds.moims.mo.mps.structures.PredictabilityEnumList;
import org.ccsds.moims.mo.mps.structures.ProfileEntry;
import org.ccsds.moims.mo.mps.structures.ProfileEntryList;
import org.ccsds.moims.mo.mps.structures.ProfileSegment;
import org.ccsds.moims.mo.mps.structures.ProfileSegmentList;
import org.ccsds.moims.mo.mps.structures.RADecDirection;
import org.ccsds.moims.mo.mps.structures.RADecDirectionList;
import org.ccsds.moims.mo.mps.structures.RelativeProfileEntry;
import org.ccsds.moims.mo.mps.structures.RelativeProfileEntryList;
import org.ccsds.moims.mo.mps.structures.RelativeProfileSegment;
import org.ccsds.moims.mo.mps.structures.RelativeProfileSegmentList;
import org.ccsds.moims.mo.mps.structures.RelativeResourceProfile;
import org.ccsds.moims.mo.mps.structures.RelativeResourceProfileList;
import org.ccsds.moims.mo.mps.structures.RequestDefinition;
import org.ccsds.moims.mo.mps.structures.RequestDefinitionList;
import org.ccsds.moims.mo.mps.structures.RequestFilter;
import org.ccsds.moims.mo.mps.structures.RequestFilterList;
import org.ccsds.moims.mo.mps.structures.RequestInstance;
import org.ccsds.moims.mo.mps.structures.RequestInstanceList;
import org.ccsds.moims.mo.mps.structures.RequestStatusEnum;
import org.ccsds.moims.mo.mps.structures.RequestStatusEnumList;
import org.ccsds.moims.mo.mps.structures.RequestStatusUpdate;
import org.ccsds.moims.mo.mps.structures.RequestStatusUpdateList;
import org.ccsds.moims.mo.mps.structures.RequestSummaryStatus;
import org.ccsds.moims.mo.mps.structures.RequestSummaryStatusList;
import org.ccsds.moims.mo.mps.structures.Resource;
import org.ccsds.moims.mo.mps.structures.ResourceList;
import org.ccsds.moims.mo.mps.structures.ResourceProfile;
import org.ccsds.moims.mo.mps.structures.ResourceProfileList;
import org.ccsds.moims.mo.mps.structures.ResourceUpdate;
import org.ccsds.moims.mo.mps.structures.ResourceUpdateList;
import org.ccsds.moims.mo.mps.structures.RevisionStatusEnum;
import org.ccsds.moims.mo.mps.structures.RevisionStatusEnumList;
import org.ccsds.moims.mo.mps.structures.RevolutionConstraint;
import org.ccsds.moims.mo.mps.structures.RevolutionConstraintList;
import org.ccsds.moims.mo.mps.structures.RevolutionRepetition;
import org.ccsds.moims.mo.mps.structures.RevolutionRepetitionList;
import org.ccsds.moims.mo.mps.structures.SecondaryErrorCodeEnum;
import org.ccsds.moims.mo.mps.structures.SecondaryErrorCodeEnumList;
import org.ccsds.moims.mo.mps.structures.SeparationConstraint;
import org.ccsds.moims.mo.mps.structures.SeparationConstraintList;
import org.ccsds.moims.mo.mps.structures.SeparationTypeEnum;
import org.ccsds.moims.mo.mps.structures.SeparationTypeEnumList;
import org.ccsds.moims.mo.mps.structures.SequentialConstraint;
import org.ccsds.moims.mo.mps.structures.SequentialConstraintList;
import org.ccsds.moims.mo.mps.structures.SimpleActivityDetails;
import org.ccsds.moims.mo.mps.structures.SimpleActivityDetailsList;
import org.ccsds.moims.mo.mps.structures.SimpleEffect;
import org.ccsds.moims.mo.mps.structures.SimpleEffectList;
import org.ccsds.moims.mo.mps.structures.SimpleResourceConstraint;
import org.ccsds.moims.mo.mps.structures.SimpleResourceConstraintList;
import org.ccsds.moims.mo.mps.structures.Slider;
import org.ccsds.moims.mo.mps.structures.SliderList;
import org.ccsds.moims.mo.mps.structures.SphericalDirection;
import org.ccsds.moims.mo.mps.structures.SphericalDirectionList;
import org.ccsds.moims.mo.mps.structures.StateDef;
import org.ccsds.moims.mo.mps.structures.StateDefList;
import org.ccsds.moims.mo.mps.structures.StatusValues;
import org.ccsds.moims.mo.mps.structures.StatusValuesList;
import org.ccsds.moims.mo.mps.structures.StringPattern;
import org.ccsds.moims.mo.mps.structures.StringPatternList;
import org.ccsds.moims.mo.mps.structures.SubPlanActivationStatus;
import org.ccsds.moims.mo.mps.structures.SubPlanActivationStatusList;
import org.ccsds.moims.mo.mps.structures.SubPlanStatusEnum;
import org.ccsds.moims.mo.mps.structures.SubPlanStatusEnumList;
import org.ccsds.moims.mo.mps.structures.SubPlanUpdate;
import org.ccsds.moims.mo.mps.structures.SubPlanUpdateList;
import org.ccsds.moims.mo.mps.structures.SurfacePosition;
import org.ccsds.moims.mo.mps.structures.SurfacePositionList;
import org.ccsds.moims.mo.mps.structures.TemporalRepetition;
import org.ccsds.moims.mo.mps.structures.TemporalRepetitionList;
import org.ccsds.moims.mo.mps.structures.TimeConstraint;
import org.ccsds.moims.mo.mps.structures.TimeConstraintList;
import org.ccsds.moims.mo.mps.structures.TimeTrigger;
import org.ccsds.moims.mo.mps.structures.TimeTriggerList;
import org.ccsds.moims.mo.mps.structures.TimeWindow;
import org.ccsds.moims.mo.mps.structures.TimeWindowConstraint;
import org.ccsds.moims.mo.mps.structures.TimeWindowConstraintList;
import org.ccsds.moims.mo.mps.structures.TimeWindowList;

/**
 * Creates the Elements of the MPS area, without holding an instance of each
 * of them, so that the class of a type is only loaded once a message carries
 * that type.
 */
public final class MPSElementFactory implements AreaElementFactory {

    @Override
    public Element createElement(int serviceNumber,
            int typeNumber) {
        if (serviceNumber != 0) {
            return null; // This Area declares no types under a service
        }
        switch (typeNumber) {
            case -517: return new PartialPlanFilterList();
            case -516: return new PlanFilterList();
            case -515: return new PartialPlanList();
            case -514: return new PlanQueryList();
            case -513: return new SubPlanActivationStatusList();
            case -512: return new SubPlanStatusEnumList();
            case -511: return new SubPlanUpdateList();
            case -510: return new PlanActivationStatusList();
            case -509: return new PlanSummaryStatusList();
            case -508: return new PlanUpdateList();
            case -507: return new RevisionStatusEnumList();
            case -506: return new ItemRevisionList();
            case -505: return new PlanRevisionList();
            case -504: return new PlannedItemsList();
            case -503: return new PlanInformationList();
            case -502: return new PlanStatusEnumList();
            case -501: return new PlanList();
            case -408: return new RequestFilterList();
            case -407: return new RequestSummaryStatusList();
            case -406: return new PlanningRequestResponseList();
            case -405: return new PlanningRequestDetailsList();
            case -404: return new RequestStatusUpdateList();
            case -403: return new RequestStatusEnumList();
            case -402: return new RequestInstanceList();
            case -401: return new RequestDefinitionList();
            case -310: return new ResourceUpdateList();
            case -309: return new RelativeProfileEntryList();
            case -308: return new RelativeProfileSegmentList();
            case -307: return new RelativeResourceProfileList();
            case -306: return new ProfileEntryList();
            case -305: return new InterpolationTypeEnumList();
            case -304: return new ProfileSegmentList();
            case -303: return new ResourceProfileList();
            case -302: return new NumericResourceList();
            case -301: return new ResourceList();
            case -206: return new InsertedEventDetailsList();
            case -205: return new EventUpdateList();
            case -204: return new PredictabilityEnumList();
            case -203: return new EventStatusEnumList();
            case -202: return new EventInstanceList();
            case -201: return new EventDefinitionList();
            case -108: return new ActivitySuspensionStatusList();
            case -107: return new InsertedActivityDetailsList();
            case -106: return new ActivityUpdateList();
            case -105: return new SimpleActivityDetailsList();
            case -104: return new ActivityNodeList();
            case -103: return new ActivityStatusEnumList();
            case -102: return new ActivityInstanceList();
            case -101: return new ActivityDefinitionList();
            case -64: return new SecondaryErrorCodeEnumList();
            case -63: return new EventRepetitionList();
            case -62: return new AngleRepetitionList();
            case -61: return new TemporalRepetitionList();
            case -60: return new RevolutionRepetitionList();
            case -59: return new DirectionRepetitionList();
            case -58: return new OrbitRepetitionList();
            case -57: return new PositionRepetitionList();
            case -56: return new SeparationTypeEnumList();
            case -55: return new EventTriggerList();
            case -54: return new AngleTriggerList();
            case -53: return new DirectionTriggerList();
            case -52: return new PositionTriggerList();
            case -51: return new TimeTriggerList();
            case -50: return new ComplexEffectList();
            case -49: return new EffectOperationEnumList();
            case -48: return new SimpleEffectList();
            case -47: return new FunctionConstraintList();
            case -46: return new SeparationConstraintList();
            case -45: return new SequentialConstraintList();
            case -44: return new AngleConstraintList();
            case -43: return new DistanceConstraintList();
            case -42: return new RevolutionConstraintList();
            case -41: return new PointingConstraintList();
            case -40: return new EllipsoidalPositionConstraintList();
            case -39: return new PositionConstraintList();
            case -38: return new ComplexResourceConstraintList();
            case -37: return new SimpleResourceConstraintList();
            case -36: return new ExpressionOperatorEnumList();
            case -35: return new ArgumentConstraintList();
            case -34: return new DurationConstraintList();
            case -33: return new TimeWindowConstraintList();
            case -32: return new TimeConstraintList();
            case -31: return new ConstraintExpressionList();
            case -30: return new LogicOpEnumList();
            case -29: return new ConstraintNodeList();
            case -28: return new StatusValuesList();
            case -27: return new StringPatternList();
            case -26: return new NumericRangeList();
            case -25: return new ArgSpecList();
            case -24: return new ArgumentList();
            case -23: return new ArgDefList();
            case -22: return new ExternalExpressionList();
            case -21: return new DistanceList();
            case -20: return new AngularVelocityList();
            case -19: return new AngleList();
            case -18: return new DirectionReferenceList();
            case -17: return new NamedTargetDirectionList();
            case -16: return new RADecDirectionList();
            case -15: return new SphericalDirectionList();
            case -14: return new CartesianDirectionList();
            case -13: return new PositionReferenceList();
            case -12: return new ObjectPositionList();
            case -11: return new OrbitalPositionList();
            case -10: return new OrbitFilePositionList();
            case -9: return new SurfacePositionList();
            case -8: return new CartesianPositionList();
            case -7: return new DefListEntryList();
            case -6: return new EventWindowList();
            case -5: return new TimeWindowList();
            case -4: return new StateDefList();
            case -3: return new SliderList();
            case -2: return new NamedElementList();
            case -1: return new ArgTypeEnumList();
            case 1: return new ArgTypeEnum();
            case 2: return new NamedElement();
            case 3: return new Slider();
            case 4: return new StateDef();
            case 5: return new TimeWindow();
            case 6: return new EventWindow();
            case 7: return new DefListEntry();
            case 8: return new CartesianPosition();
            case 9: return new SurfacePosition();
            case 10: return new OrbitFilePosition();
            case 11: return new OrbitalPosition();
            case 12: return new ObjectPosition();
            case 13: return new PositionReference();
            case 14: return new CartesianDirection();
            case 15: return new SphericalDirection();
            case 16: return new RADecDirection();
            case 17: return new NamedTargetDirection();
            case 18: return new DirectionReference();
            case 19: return new Angle();
            case 20: return new AngularVelocity();
            case 21: return new Distance();
            case 22: return new ExternalExpression();
            case 23: return new ArgDef();
            case 24: return new Argument();
            case 25: return new ArgSpec();
            case 26: return new NumericRange();
            case 27: return new StringPattern();
            case 28: return new StatusValues();
            case 29: return new ConstraintNode();
            case 30: return new LogicOpEnum();
            case 31: return new ConstraintExpression();
            case 32: return new TimeConstraint();
            case 33: return new TimeWindowConstraint();
            case 34: return new DurationConstraint();
            case 35: return new ArgumentConstraint();
            case 36: return new ExpressionOperatorEnum();
            case 37: return new SimpleResourceConstraint();
            case 38: return new ComplexResourceConstraint();
            case 39: return new PositionConstraint();
            case 40: return new EllipsoidalPositionConstraint();
            case 41: return new PointingConstraint();
            case 42: return new RevolutionConstraint();
            case 43: return new DistanceConstraint();
            case 44: return new AngleConstraint();
            case 45: return new SequentialConstraint();
            case 46: return new SeparationConstraint();
            case 47: return new FunctionConstraint();
            case 48: return new SimpleEffect();
            case 49: return new EffectOperationEnum();
            case 50: return new ComplexEffect();
            case 51: return new TimeTrigger();
            case 52: return new PositionTrigger();
            case 53: return new DirectionTrigger();
            case 54: return new AngleTrigger();
            case 55: return new EventTrigger();
            case 56: return new SeparationTypeEnum();
            case 57: return new PositionRepetition();
            case 58: return new OrbitRepetition();
            case 59: return new DirectionRepetition();
            case 60: return new RevolutionRepetition();
            case 61: return new TemporalRepetition();
            case 62: return new AngleRepetition();
            case 63: return new EventRepetition();
            case 64: return new SecondaryErrorCodeEnum();
            case 101: return new ActivityDefinition();
            case 102: return new ActivityInstance();
            case 103: return new ActivityStatusEnum();
            case 104: return new ActivityNode();
            case 105: return new SimpleActivityDetails();
            case 106: return new ActivityUpdate();
            case 107: return new InsertedActivityDetails();
            case 108: return new ActivitySuspensionStatus();
            case 201: return new EventDefinition();
            case 202: return new EventInstance();
            case 203: return new EventStatusEnum();
            case 204: return new PredictabilityEnum();
            case 205: return new EventUpdate();
            case 206: return new InsertedEventDetails();
            case 301: return new Resource();
            case 302: return new NumericResource();
            case 303: return new ResourceProfile();
            case 304: return new ProfileSegment();
            case 305: return new InterpolationTypeEnum();
            case 306: return new ProfileEntry();
            case 307: return new RelativeResourceProfile();
            case 308: return new RelativeProfileSegment();
            case 309: return new RelativeProfileEntry();
            case 310: return new ResourceUpdate();
            case 401: return new RequestDefinition();
            case 402: return new RequestInstance();
            case 403: return new RequestStatusEnum();
            case 404: return new RequestStatusUpdate();
            case 405: return new PlanningRequestDetails();
            case 406: return new PlanningRequestResponse();
            case 407: return new RequestSummaryStatus();
            case 408: return new RequestFilter();
            case 501: return new Plan();
            case 502: return new PlanStatusEnum();
            case 503: return new PlanInformation();
            case 504: return new PlannedItems();
            case 505: return new PlanRevision();
            case 506: return new ItemRevision();
            case 507: return new RevisionStatusEnum();
            case 508: return new PlanUpdate();
            case 509: return new PlanSummaryStatus();
            case 510: return new PlanActivationStatus();
            case 511: return new SubPlanUpdate();
            case 512: return new SubPlanStatusEnum();
            case 513: return new SubPlanActivationStatus();
            case 514: return new PlanQuery();
            case 515: return new PartialPlan();
            case 516: return new PlanFilter();
            case 517: return new PartialPlanFilter();
            default: return createAreaElementOutOfBand(typeNumber);
        }
    }

    @Override
    public int getAreaNumber() {
        return 5;
    }

    @Override
    public int getAreaVersion() {
        return 1;
    }

    /**
     * Creates an Element whose type number lies too far out to be held in the
     * jump table that is asked first. This says nothing about how often the type
     * is asked for: the numbers of an Area are not handed out in the order of
     * use.
     * 
     * @param typeNumber The typeNumber field.
     */
    private static Element createAreaElementOutOfBand(int typeNumber) {
        switch (typeNumber) {
            case -702: return new FunctionDetailsList();
            case -701: return new FunctionDefinitionDetailsList();
            case -601: return new PlanningUserList();
            case 601: return new PlanningUser();
            case 701: return new FunctionDefinitionDetails();
            case 702: return new FunctionDetails();
            default: return null;
        }
    }

}
