# ----------------------------------------------------------------------------
# Copyright (C) 2013      European Space Agency
#                         European Space Operations Centre
#                         Darmstadt
#                         Germany
# ----------------------------------------------------------------------------
# System                : CCSDS MO Test bed utilities
# ----------------------------------------------------------------------------
# Licensed under the European Space Agency Public License, Version 2.0
# You may not use this file except in compliance with the License.
#
# Except as expressly set forth in this License, the Software is provided to
# You on an "as is" basis and without warranties of any kind, including without
# limitation merchantability, fitness for a particular purpose, absence of
# defects or errors, accuracy or non-infringement of intellectual property rights.
# 
# See the License for the specific language governing permissions and
# limitations under the License. 
# ----------------------------------------------------------------------------

# Do not assign specific port to avoid "Address already in use" exception
#org.ccsds.moims.mo.mal.transport.http.port=61617
org.ccsds.moims.mo.mal.transport.http.host=localhost
org.ccsds.moims.mo.mal.transport.http.timeout=5
org.ccsds.moims.mo.mal.transport.http.debug=FINEST
#org.ccsds.moims.mo.mal.transport.http.serverimpl=esa.mo.mal.transport.http.api.jetty.JettyServer
#org.ccsds.moims.mo.mal.transport.http.clientimpl=esa.mo.mal.transport.http.api.jetty.JettyClient
