/* ----------------------------------------------------------------------------
 * Copyright (C) 2023      European Space Agency
 *                         European Space Operations Centre
 *                         Darmstadt
 *                         Germany
 * ----------------------------------------------------------------------------
 * System                : ESA MO Navigator
 * ----------------------------------------------------------------------------
 * Licensed under the European Space Agency Public License, Version 2.0
 * You may not use this file except in compliance with the License.
 *
 * Except as expressly set forth in this License, the Software is provided to
 * You on an "as is" basis and without warranties of any kind, including without
 * limitation merchantability, fitness for a particular purpose, absence of
 * defects or errors, accuracy or non-infringement of intellectual property rights.
 * 
 * See the License for the specific language governing permissions and
 * limitations under the License. 
 * ----------------------------------------------------------------------------
 */
package esa.mo.navigator;

import java.awt.Cursor;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 * This class provides a simple form for the control of the consumer.
 */
public class AppGUI extends javax.swing.JFrame {

    private final static String FRAME_NAME = "MO Navigator";
    //private final static String DEFAULT_XMLS_DIR = "_xmls";
    private final static String DEFAULT_XMLS_DIR = "../../xml-service-specifications/xml-ccsds-mo-prototypes/src/main/resources/xml";

    /**
     * Creates the GUI form
     *
     */
    public AppGUI() {
        initComponents();
    }

    /**
     * Main command line entry point.
     *
     * @param args the command line arguments
     */
    public static void main(final String args[]) {
        try {
            String systemLookAndFeel = UIManager.getSystemLookAndFeelClassName();
            // If the Look and Feel is not the default
            if (systemLookAndFeel != null && systemLookAndFeel.contains("MetalLookAndFeel")) {
                // If it is the default, then adapt the size of the font
                UILookAndFeel.adaptFontSizeToDisplay();
            } else {
                UIManager.setLookAndFeel(systemLookAndFeel); // Set as the system
            }
        } catch (UnsupportedLookAndFeelException e) {
        } catch (ClassNotFoundException e) {
        } catch (InstantiationException e) {
        } catch (IllegalAccessException e) {
            // handle exception
        }

        final AppGUI gui = new AppGUI();
        gui.init();
        gui.setVisible(true);
    }

    /**
     * Initializes the GUI
     *
     */
    public void init() {
        this.setLocationRelativeTo(null);
        this.setTitle(AppGUI.FRAME_NAME);

        this.prepareTopBar();
        this.bottomPanel.setVisible(true);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);

        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                closeApplication();
            }
        });

        middlePanel.add(new MiddlePanel(statusLabel, new File(DEFAULT_XMLS_DIR)));
        statusLabel.setText("Ready!");
    }

    private void closeApplication() {
        boolean areYouSure = true;
        /*
        boolean areYouSure = false;

        if (JOptionPane.showConfirmDialog(null,
                "Are you sure you want to exit the App?",
                "Are you sure?",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
            areYouSure = true;
        }
        */

        if (areYouSure) {
            this.exitApplication();
        }
    }

    private void exitApplication() {
        System.exit(0);
    }

    private void prepareTopBar() {
        topLabel.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
            }
        });

        cornerPanel.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        cornerPanel.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
            }
        });
        
        this.topLabel.setText("");
        this.topPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        topLabel = new javax.swing.JLabel();
        cornerPanel = new javax.swing.JPanel();
        topRightCornerLabel = new javax.swing.JLabel();
        spacerLabel = new javax.swing.JLabel();
        middlePanel = new javax.swing.JPanel();
        bottomPanel = new javax.swing.JPanel();
        statusLabel = new javax.swing.JLabel();
        rightSidePanel = new javax.swing.JPanel();
        bottomRightCornerLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Title");
        setMinimumSize(new java.awt.Dimension(800, 600));
        setName("Form"); // NOI18N
        getContentPane().setLayout(new java.awt.BorderLayout(5, 2));

        topPanel.setMinimumSize(new java.awt.Dimension(100, 22));
        topPanel.setName("topPanel"); // NOI18N
        topPanel.setLayout(new java.awt.BorderLayout());

        topLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        topLabel.setText("A picture");
        topLabel.setName("topLabel"); // NOI18N
        topPanel.add(topLabel, java.awt.BorderLayout.CENTER);

        cornerPanel.setName("cornerPanel"); // NOI18N
        cornerPanel.setLayout(new java.awt.BorderLayout());

        topRightCornerLabel.setText("My corner label");
        topRightCornerLabel.setName("topRightCornerLabel"); // NOI18N
        cornerPanel.add(topRightCornerLabel, java.awt.BorderLayout.CENTER);

        spacerLabel.setText("     ");
        spacerLabel.setName("spacerLabel"); // NOI18N
        cornerPanel.add(spacerLabel, java.awt.BorderLayout.LINE_END);

        topPanel.add(cornerPanel, java.awt.BorderLayout.LINE_END);

        getContentPane().add(topPanel, java.awt.BorderLayout.PAGE_START);

        middlePanel.setName("middlePanel"); // NOI18N
        middlePanel.setLayout(new java.awt.BorderLayout());
        getContentPane().add(middlePanel, java.awt.BorderLayout.CENTER);

        bottomPanel.setMinimumSize(new java.awt.Dimension(318, 20));
        bottomPanel.setName("bottomPanel"); // NOI18N
        bottomPanel.setLayout(new java.awt.BorderLayout());

        statusLabel.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        statusLabel.setText("A status bar");
        statusLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 0));
        statusLabel.setName("statusLabel"); // NOI18N
        statusLabel.setPreferredSize(new java.awt.Dimension(298, 40));
        bottomPanel.add(statusLabel, java.awt.BorderLayout.CENTER);

        rightSidePanel.setName("rightSidePanel"); // NOI18N

        bottomRightCornerLabel.setText("  ");
        bottomRightCornerLabel.setName("bottomRightCornerLabel"); // NOI18N
        rightSidePanel.add(bottomRightCornerLabel);

        bottomPanel.add(rightSidePanel, java.awt.BorderLayout.LINE_END);

        getContentPane().add(bottomPanel, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JLabel bottomRightCornerLabel;
    private javax.swing.JPanel cornerPanel;
    private javax.swing.JPanel middlePanel;
    private javax.swing.JPanel rightSidePanel;
    private javax.swing.JLabel spacerLabel;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JLabel topLabel;
    private javax.swing.JPanel topPanel;
    private javax.swing.JLabel topRightCornerLabel;
    // End of variables declaration//GEN-END:variables
}
