//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.15 at 03:22:23 PM CET 
//


package esa.mo.xsd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * List that contains one or more data type definitions including those only allowed in the MAL Area.
 * 
 * <p>Java class for AreaDataTypeList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AreaDataTypeList"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.ccsds.org/schema/ServiceSchema}DocumentationBaseType"&gt;
 *       &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *         &lt;element name="fundamental" type="{http://www.ccsds.org/schema/ServiceSchema}FundamentalType"/&gt;
 *         &lt;element name="attribute" type="{http://www.ccsds.org/schema/ServiceSchema}AttributeType"/&gt;
 *         &lt;element name="composite" type="{http://www.ccsds.org/schema/ServiceSchema}CompositeType"/&gt;
 *         &lt;element name="enumeration" type="{http://www.ccsds.org/schema/ServiceSchema}EnumerationType"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AreaDataTypeList", namespace = "http://www.ccsds.org/schema/ServiceSchema", propOrder = {
    "fundamentalOrAttributeOrComposite"
})
public class AreaDataTypeList
    extends DocumentationBaseType
{

    @XmlElements({
        @XmlElement(name = "fundamental", namespace = "http://www.ccsds.org/schema/ServiceSchema", type = FundamentalType.class),
        @XmlElement(name = "attribute", namespace = "http://www.ccsds.org/schema/ServiceSchema", type = AttributeType.class),
        @XmlElement(name = "composite", namespace = "http://www.ccsds.org/schema/ServiceSchema", type = CompositeType.class),
        @XmlElement(name = "enumeration", namespace = "http://www.ccsds.org/schema/ServiceSchema", type = EnumerationType.class)
    })
    protected List<Object> fundamentalOrAttributeOrComposite;

    /**
     * Gets the value of the fundamentalOrAttributeOrComposite property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fundamentalOrAttributeOrComposite property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFundamentalOrAttributeOrComposite().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FundamentalType }
     * {@link AttributeType }
     * {@link CompositeType }
     * {@link EnumerationType }
     * 
     * 
     */
    public List<Object> getFundamentalOrAttributeOrComposite() {
        if (fundamentalOrAttributeOrComposite == null) {
            fundamentalOrAttributeOrComposite = new ArrayList<Object>();
        }
        return this.fundamentalOrAttributeOrComposite;
    }

}
