//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.15 at 03:22:23 PM CET 
//


package esa.mo.xsd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Element that represents a Capability set, contains one or more operation specification.
 * 
 * <p>Java class for CapabilitySetType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CapabilitySetType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;element name="sendIP" type="{http://www.ccsds.org/schema/ServiceSchema}SendOperationType"/&gt;
 *           &lt;element name="submitIP" type="{http://www.ccsds.org/schema/ServiceSchema}SubmitOperationType"/&gt;
 *           &lt;element name="requestIP" type="{http://www.ccsds.org/schema/ServiceSchema}RequestOperationType"/&gt;
 *           &lt;element name="invokeIP" type="{http://www.ccsds.org/schema/ServiceSchema}InvokeOperationType"/&gt;
 *           &lt;element name="progressIP" type="{http://www.ccsds.org/schema/ServiceSchema}ProgressOperationType"/&gt;
 *           &lt;element name="pubsubIP" type="{http://www.ccsds.org/schema/ServiceSchema}PubSubOperationType"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="number" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" /&gt;
 *       &lt;attribute name="comment" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CapabilitySetType", namespace = "http://www.ccsds.org/schema/ServiceSchema", propOrder = {
    "sendIPOrSubmitIPOrRequestIP"
})
public class CapabilitySetType {

    @XmlElements({
        @XmlElement(name = "sendIP", namespace = "http://www.ccsds.org/schema/ServiceSchema", type = SendOperationType.class),
        @XmlElement(name = "submitIP", namespace = "http://www.ccsds.org/schema/ServiceSchema", type = SubmitOperationType.class),
        @XmlElement(name = "requestIP", namespace = "http://www.ccsds.org/schema/ServiceSchema", type = RequestOperationType.class),
        @XmlElement(name = "invokeIP", namespace = "http://www.ccsds.org/schema/ServiceSchema", type = InvokeOperationType.class),
        @XmlElement(name = "progressIP", namespace = "http://www.ccsds.org/schema/ServiceSchema", type = ProgressOperationType.class),
        @XmlElement(name = "pubsubIP", namespace = "http://www.ccsds.org/schema/ServiceSchema", type = PubSubOperationType.class)
    })
    protected List<OperationType> sendIPOrSubmitIPOrRequestIP;
    @XmlAttribute(name = "number", required = true)
    @XmlSchemaType(name = "unsignedShort")
    protected int number;
    @XmlAttribute(name = "comment")
    protected String comment;

    /**
     * Gets the value of the sendIPOrSubmitIPOrRequestIP property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sendIPOrSubmitIPOrRequestIP property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSendIPOrSubmitIPOrRequestIP().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SendOperationType }
     * {@link SubmitOperationType }
     * {@link RequestOperationType }
     * {@link InvokeOperationType }
     * {@link ProgressOperationType }
     * {@link PubSubOperationType }
     * 
     * 
     */
    public List<OperationType> getSendIPOrSubmitIPOrRequestIP() {
        if (sendIPOrSubmitIPOrRequestIP == null) {
            sendIPOrSubmitIPOrRequestIP = new ArrayList<OperationType>();
        }
        return this.sendIPOrSubmitIPOrRequestIP;
    }

    /**
     * Gets the value of the number property.
     * 
     */
    public int getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     * 
     */
    public void setNumber(int value) {
        this.number = value;
    }

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComment(String value) {
        this.comment = value;
    }

}
