//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.15 at 03:22:23 PM CET 
//


package esa.mo.xsd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Represents a composite type.
 * 
 * <p>Java class for CompositeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CompositeType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="extends" type="{http://www.ccsds.org/schema/ServiceSchema}ElementReferenceType" minOccurs="0"/&gt;
 *         &lt;element name="field" type="{http://www.ccsds.org/schema/ServiceSchema}NamedElementReferenceWithCommentType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" /&gt;
 *       &lt;attribute name="shortFormPart" type="{http://www.ccsds.org/schema/ServiceSchema}ShortFormPart" /&gt;
 *       &lt;attribute name="comment" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CompositeType", namespace = "http://www.ccsds.org/schema/ServiceSchema", propOrder = {
    "_extends",
    "field"
})
public class CompositeType {

    @XmlElement(name = "extends", namespace = "http://www.ccsds.org/schema/ServiceSchema")
    protected ElementReferenceType _extends;
    @XmlElement(namespace = "http://www.ccsds.org/schema/ServiceSchema")
    protected List<NamedElementReferenceWithCommentType> field;
    @XmlAttribute(name = "name", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String name;
    @XmlAttribute(name = "shortFormPart")
    protected Long shortFormPart;
    @XmlAttribute(name = "comment")
    protected String comment;

    /**
     * Gets the value of the extends property.
     * 
     * @return
     *     possible object is
     *     {@link ElementReferenceType }
     *     
     */
    public ElementReferenceType getExtends() {
        return _extends;
    }

    /**
     * Sets the value of the extends property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElementReferenceType }
     *     
     */
    public void setExtends(ElementReferenceType value) {
        this._extends = value;
    }

    /**
     * Gets the value of the field property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the field property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getField().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NamedElementReferenceWithCommentType }
     * 
     * 
     */
    public List<NamedElementReferenceWithCommentType> getField() {
        if (field == null) {
            field = new ArrayList<NamedElementReferenceWithCommentType>();
        }
        return this.field;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the shortFormPart property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getShortFormPart() {
        return shortFormPart;
    }

    /**
     * Sets the value of the shortFormPart property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setShortFormPart(Long value) {
        this.shortFormPart = value;
    }

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComment(String value) {
        this.comment = value;
    }

}
