//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.15 at 03:22:23 PM CET 
//


package esa.mo.xsd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DocumentationBaseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DocumentationBaseType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="documentation" type="{http://www.ccsds.org/schema/ServiceSchema}DocumentationType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="diagram" type="{http://www.ccsds.org/schema/ServiceSchema}AnyTypeReferenceWithId" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DocumentationBaseType", namespace = "http://www.ccsds.org/schema/ServiceSchema", propOrder = {
    "documentation",
    "diagram"
})
@XmlSeeAlso({
    SupportedFeatures.class,
    AreaType.class,
    ServiceType.class,
    AreaDataTypeList.class,
    DataTypeList.class
})
public class DocumentationBaseType {

    @XmlElement(namespace = "http://www.ccsds.org/schema/ServiceSchema")
    protected List<DocumentationType> documentation;
    @XmlElement(namespace = "http://www.ccsds.org/schema/ServiceSchema")
    protected List<AnyTypeReferenceWithId> diagram;

    /**
     * Gets the value of the documentation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DocumentationType }
     * 
     * 
     */
    public List<DocumentationType> getDocumentation() {
        if (documentation == null) {
            documentation = new ArrayList<DocumentationType>();
        }
        return this.documentation;
    }

    /**
     * Gets the value of the diagram property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the diagram property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDiagram().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AnyTypeReferenceWithId }
     * 
     * 
     */
    public List<AnyTypeReferenceWithId> getDiagram() {
        if (diagram == null) {
            diagram = new ArrayList<AnyTypeReferenceWithId>();
        }
        return this.diagram;
    }

}
