//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.15 at 03:22:23 PM CET 
//


package esa.mo.xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Used to reference an existing Error condition
 * 
 * <p>Java class for ErrorReferenceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ErrorReferenceType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.ccsds.org/schema/ServiceSchema}ElementReferenceWithCommentType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="extraInformation" type="{http://www.ccsds.org/schema/ServiceSchema}ElementReferenceWithCommentType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ErrorReferenceType", namespace = "http://www.ccsds.org/schema/ServiceSchema", propOrder = {
    "extraInformation"
})
public class ErrorReferenceType
    extends ElementReferenceWithCommentType
{

    @XmlElement(namespace = "http://www.ccsds.org/schema/ServiceSchema")
    protected ElementReferenceWithCommentType extraInformation;

    /**
     * Gets the value of the extraInformation property.
     * 
     * @return
     *     possible object is
     *     {@link ElementReferenceWithCommentType }
     *     
     */
    public ElementReferenceWithCommentType getExtraInformation() {
        return extraInformation;
    }

    /**
     * Sets the value of the extraInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElementReferenceWithCommentType }
     *     
     */
    public void setExtraInformation(ElementReferenceWithCommentType value) {
        this.extraInformation = value;
    }

}
