//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.15 at 03:22:23 PM CET 
//


package esa.mo.xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Element represents a Service specification inside an Area. May optionally extend the COM capability sets and include Capability set. May also optionally include data type and error definitions.
 * 
 * <p>Java class for ExtendedServiceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExtendedServiceType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.ccsds.org/schema/ServiceSchema}ServiceType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="features" type="{http://www.ccsds.org/schema/COMSchema}SupportedFeatures" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExtendedServiceType", namespace = "http://www.ccsds.org/schema/COMSchema", propOrder = {
    "features"
})
public class ExtendedServiceType
    extends ServiceType
{

    @XmlElement(namespace = "http://www.ccsds.org/schema/COMSchema")
    protected SupportedFeatures features;

    /**
     * Gets the value of the features property.
     * 
     * @return
     *     possible object is
     *     {@link SupportedFeatures }
     *     
     */
    public SupportedFeatures getFeatures() {
        return features;
    }

    /**
     * Sets the value of the features property.
     * 
     * @param value
     *     allowed object is
     *     {@link SupportedFeatures }
     *     
     */
    public void setFeatures(SupportedFeatures value) {
        this.features = value;
    }

}
