//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.15 at 03:22:23 PM CET 
//


package esa.mo.xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Defines how a service represents an aspect of the COM.
 * 
 * <p>Java class for ModelObjectType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ModelObjectType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="objectType" type="{http://www.ccsds.org/schema/ServiceSchema}AnyTypeReference" minOccurs="0"/&gt;
 *         &lt;element name="relatedObject" type="{http://www.ccsds.org/schema/COMSchema}OptionalObjectReference" minOccurs="0"/&gt;
 *         &lt;element name="sourceObject" type="{http://www.ccsds.org/schema/COMSchema}OptionalObjectReference" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" /&gt;
 *       &lt;attribute name="number" use="required" type="{http://www.ccsds.org/schema/ServiceSchema}ShortFormPart" /&gt;
 *       &lt;attribute name="comment" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ModelObjectType", namespace = "http://www.ccsds.org/schema/COMSchema", propOrder = {
    "objectType",
    "relatedObject",
    "sourceObject"
})
public class ModelObjectType {

    @XmlElement(namespace = "http://www.ccsds.org/schema/COMSchema")
    protected AnyTypeReference objectType;
    @XmlElement(namespace = "http://www.ccsds.org/schema/COMSchema")
    protected OptionalObjectReference relatedObject;
    @XmlElement(namespace = "http://www.ccsds.org/schema/COMSchema")
    protected OptionalObjectReference sourceObject;
    @XmlAttribute(name = "name", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String name;
    @XmlAttribute(name = "number", required = true)
    protected long number;
    @XmlAttribute(name = "comment")
    protected String comment;

    /**
     * Gets the value of the objectType property.
     * 
     * @return
     *     possible object is
     *     {@link AnyTypeReference }
     *     
     */
    public AnyTypeReference getObjectType() {
        return objectType;
    }

    /**
     * Sets the value of the objectType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnyTypeReference }
     *     
     */
    public void setObjectType(AnyTypeReference value) {
        this.objectType = value;
    }

    /**
     * Gets the value of the relatedObject property.
     * 
     * @return
     *     possible object is
     *     {@link OptionalObjectReference }
     *     
     */
    public OptionalObjectReference getRelatedObject() {
        return relatedObject;
    }

    /**
     * Sets the value of the relatedObject property.
     * 
     * @param value
     *     allowed object is
     *     {@link OptionalObjectReference }
     *     
     */
    public void setRelatedObject(OptionalObjectReference value) {
        this.relatedObject = value;
    }

    /**
     * Gets the value of the sourceObject property.
     * 
     * @return
     *     possible object is
     *     {@link OptionalObjectReference }
     *     
     */
    public OptionalObjectReference getSourceObject() {
        return sourceObject;
    }

    /**
     * Sets the value of the sourceObject property.
     * 
     * @param value
     *     allowed object is
     *     {@link OptionalObjectReference }
     *     
     */
    public void setSourceObject(OptionalObjectReference value) {
        this.sourceObject = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the number property.
     * 
     */
    public long getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     * 
     */
    public void setNumber(long value) {
        this.number = value;
    }

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComment(String value) {
        this.comment = value;
    }

}
