//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.15 at 03:22:23 PM CET 
//


package esa.mo.xsd;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the esa.mo.xsd package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Specification_QNAME = new QName("http://www.ccsds.org/schema/ServiceSchema", "specification");
    private final static QName _Field_QNAME = new QName("http://www.ccsds.org/schema/ServiceSchema", "field");
    private final static QName _Type_QNAME = new QName("http://www.ccsds.org/schema/ServiceSchema", "type");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: esa.mo.xsd
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EnumerationType }
     * 
     */
    public EnumerationType createEnumerationType() {
        return new EnumerationType();
    }

    /**
     * Create an instance of {@link PubSubOperationType }
     * 
     */
    public PubSubOperationType createPubSubOperationType() {
        return new PubSubOperationType();
    }

    /**
     * Create an instance of {@link ProgressOperationType }
     * 
     */
    public ProgressOperationType createProgressOperationType() {
        return new ProgressOperationType();
    }

    /**
     * Create an instance of {@link InvokeOperationType }
     * 
     */
    public InvokeOperationType createInvokeOperationType() {
        return new InvokeOperationType();
    }

    /**
     * Create an instance of {@link RequestOperationType }
     * 
     */
    public RequestOperationType createRequestOperationType() {
        return new RequestOperationType();
    }

    /**
     * Create an instance of {@link SubmitOperationType }
     * 
     */
    public SubmitOperationType createSubmitOperationType() {
        return new SubmitOperationType();
    }

    /**
     * Create an instance of {@link SendOperationType }
     * 
     */
    public SendOperationType createSendOperationType() {
        return new SendOperationType();
    }

    /**
     * Create an instance of {@link ExtendedServiceType }
     * 
     */
    public ExtendedServiceType createExtendedServiceType() {
        return new ExtendedServiceType();
    }

    /**
     * Create an instance of {@link SupportedFeatures }
     * 
     */
    public SupportedFeatures createSupportedFeatures() {
        return new SupportedFeatures();
    }

    /**
     * Create an instance of {@link ModelObjectTypeList }
     * 
     */
    public ModelObjectTypeList createModelObjectTypeList() {
        return new ModelObjectTypeList();
    }

    /**
     * Create an instance of {@link ModelObjectType }
     * 
     */
    public ModelObjectType createModelObjectType() {
        return new ModelObjectType();
    }

    /**
     * Create an instance of {@link ModelEventTypeList }
     * 
     */
    public ModelEventTypeList createModelEventTypeList() {
        return new ModelEventTypeList();
    }

    /**
     * Create an instance of {@link OptionalObjectReference }
     * 
     */
    public OptionalObjectReference createOptionalObjectReference() {
        return new OptionalObjectReference();
    }

    /**
     * Create an instance of {@link ObjectReference }
     * 
     */
    public ObjectReference createObjectReference() {
        return new ObjectReference();
    }

    /**
     * Create an instance of {@link CommentType }
     * 
     */
    public CommentType createCommentType() {
        return new CommentType();
    }

    /**
     * Create an instance of {@link SpecificationType }
     * 
     */
    public SpecificationType createSpecificationType() {
        return new SpecificationType();
    }

    /**
     * Create an instance of {@link NamedElementReferenceWithCommentType }
     * 
     */
    public NamedElementReferenceWithCommentType createNamedElementReferenceWithCommentType() {
        return new NamedElementReferenceWithCommentType();
    }

    /**
     * Create an instance of {@link TypeReference }
     * 
     */
    public TypeReference createTypeReference() {
        return new TypeReference();
    }

    /**
     * Create an instance of {@link AreaType }
     * 
     */
    public AreaType createAreaType() {
        return new AreaType();
    }

    /**
     * Create an instance of {@link ServiceType }
     * 
     */
    public ServiceType createServiceType() {
        return new ServiceType();
    }

    /**
     * Create an instance of {@link CapabilitySetType }
     * 
     */
    public CapabilitySetType createCapabilitySetType() {
        return new CapabilitySetType();
    }

    /**
     * Create an instance of {@link AreaDataTypeList }
     * 
     */
    public AreaDataTypeList createAreaDataTypeList() {
        return new AreaDataTypeList();
    }

    /**
     * Create an instance of {@link DataTypeList }
     * 
     */
    public DataTypeList createDataTypeList() {
        return new DataTypeList();
    }

    /**
     * Create an instance of {@link OperationErrorList }
     * 
     */
    public OperationErrorList createOperationErrorList() {
        return new OperationErrorList();
    }

    /**
     * Create an instance of {@link ErrorDefinitionList }
     * 
     */
    public ErrorDefinitionList createErrorDefinitionList() {
        return new ErrorDefinitionList();
    }

    /**
     * Create an instance of {@link ErrorDefinitionType }
     * 
     */
    public ErrorDefinitionType createErrorDefinitionType() {
        return new ErrorDefinitionType();
    }

    /**
     * Create an instance of {@link ErrorReferenceType }
     * 
     */
    public ErrorReferenceType createErrorReferenceType() {
        return new ErrorReferenceType();
    }

    /**
     * Create an instance of {@link FundamentalType }
     * 
     */
    public FundamentalType createFundamentalType() {
        return new FundamentalType();
    }

    /**
     * Create an instance of {@link AttributeType }
     * 
     */
    public AttributeType createAttributeType() {
        return new AttributeType();
    }

    /**
     * Create an instance of {@link CompositeType }
     * 
     */
    public CompositeType createCompositeType() {
        return new CompositeType();
    }

    /**
     * Create an instance of {@link ElementReferenceWithCommentType }
     * 
     */
    public ElementReferenceWithCommentType createElementReferenceWithCommentType() {
        return new ElementReferenceWithCommentType();
    }

    /**
     * Create an instance of {@link ElementReferenceType }
     * 
     */
    public ElementReferenceType createElementReferenceType() {
        return new ElementReferenceType();
    }

    /**
     * Create an instance of {@link DocumentationBaseType }
     * 
     */
    public DocumentationBaseType createDocumentationBaseType() {
        return new DocumentationBaseType();
    }

    /**
     * Create an instance of {@link DocumentationType }
     * 
     */
    public DocumentationType createDocumentationType() {
        return new DocumentationType();
    }

    /**
     * Create an instance of {@link AnyTypeReferenceWithId }
     * 
     */
    public AnyTypeReferenceWithId createAnyTypeReferenceWithId() {
        return new AnyTypeReferenceWithId();
    }

    /**
     * Create an instance of {@link AnyTypeReference }
     * 
     */
    public AnyTypeReference createAnyTypeReference() {
        return new AnyTypeReference();
    }

    /**
     * Create an instance of {@link EnumerationType.Item }
     * 
     */
    public EnumerationType.Item createEnumerationTypeItem() {
        return new EnumerationType.Item();
    }

    /**
     * Create an instance of {@link PubSubOperationType.Messages }
     * 
     */
    public PubSubOperationType.Messages createPubSubOperationTypeMessages() {
        return new PubSubOperationType.Messages();
    }

    /**
     * Create an instance of {@link ProgressOperationType.Messages }
     * 
     */
    public ProgressOperationType.Messages createProgressOperationTypeMessages() {
        return new ProgressOperationType.Messages();
    }

    /**
     * Create an instance of {@link InvokeOperationType.Messages }
     * 
     */
    public InvokeOperationType.Messages createInvokeOperationTypeMessages() {
        return new InvokeOperationType.Messages();
    }

    /**
     * Create an instance of {@link RequestOperationType.Messages }
     * 
     */
    public RequestOperationType.Messages createRequestOperationTypeMessages() {
        return new RequestOperationType.Messages();
    }

    /**
     * Create an instance of {@link SubmitOperationType.Messages }
     * 
     */
    public SubmitOperationType.Messages createSubmitOperationTypeMessages() {
        return new SubmitOperationType.Messages();
    }

    /**
     * Create an instance of {@link SendOperationType.Messages }
     * 
     */
    public SendOperationType.Messages createSendOperationTypeMessages() {
        return new SendOperationType.Messages();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SpecificationType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SpecificationType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ccsds.org/schema/ServiceSchema", name = "specification")
    public JAXBElement<SpecificationType> createSpecification(SpecificationType value) {
        return new JAXBElement<SpecificationType>(_Specification_QNAME, SpecificationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NamedElementReferenceWithCommentType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link NamedElementReferenceWithCommentType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ccsds.org/schema/ServiceSchema", name = "field")
    public JAXBElement<NamedElementReferenceWithCommentType> createField(NamedElementReferenceWithCommentType value) {
        return new JAXBElement<NamedElementReferenceWithCommentType>(_Field_QNAME, NamedElementReferenceWithCommentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeReference }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TypeReference }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ccsds.org/schema/ServiceSchema", name = "type")
    public JAXBElement<TypeReference> createType(TypeReference value) {
        return new JAXBElement<TypeReference>(_Type_QNAME, TypeReference.class, null, value);
    }

}
