//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.15 at 03:22:23 PM CET 
//


package esa.mo.xsd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * Represents that list of Errors that an operation may raise, these may reference existing error definitions or define new ones.
 * 
 * <p>Java class for OperationErrorList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OperationErrorList"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice maxOccurs="unbounded"&gt;
 *         &lt;element name="error" type="{http://www.ccsds.org/schema/ServiceSchema}ErrorDefinitionType"/&gt;
 *         &lt;element name="errorRef" type="{http://www.ccsds.org/schema/ServiceSchema}ErrorReferenceType"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OperationErrorList", namespace = "http://www.ccsds.org/schema/ServiceSchema", propOrder = {
    "errorOrErrorRef"
})
public class OperationErrorList {

    @XmlElements({
        @XmlElement(name = "error", namespace = "http://www.ccsds.org/schema/ServiceSchema", type = ErrorDefinitionType.class),
        @XmlElement(name = "errorRef", namespace = "http://www.ccsds.org/schema/ServiceSchema", type = ErrorReferenceType.class)
    })
    protected List<Object> errorOrErrorRef;

    /**
     * Gets the value of the errorOrErrorRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the errorOrErrorRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getErrorOrErrorRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ErrorDefinitionType }
     * {@link ErrorReferenceType }
     * 
     * 
     */
    public List<Object> getErrorOrErrorRef() {
        if (errorOrErrorRef == null) {
            errorOrErrorRef = new ArrayList<Object>();
        }
        return this.errorOrErrorRef;
    }

}
