//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.15 at 03:22:23 PM CET 
//


package esa.mo.xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Element represents a SEND operation.
 * 
 * <p>Java class for SendOperationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SendOperationType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.ccsds.org/schema/ServiceSchema}OperationType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="messages"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="send" type="{http://www.ccsds.org/schema/ServiceSchema}AnyTypeReference"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SendOperationType", namespace = "http://www.ccsds.org/schema/ServiceSchema", propOrder = {
    "messages"
})
public class SendOperationType
    extends OperationType
{

    @XmlElement(namespace = "http://www.ccsds.org/schema/ServiceSchema", required = true)
    protected SendOperationType.Messages messages;

    /**
     * Gets the value of the messages property.
     * 
     * @return
     *     possible object is
     *     {@link SendOperationType.Messages }
     *     
     */
    public SendOperationType.Messages getMessages() {
        return messages;
    }

    /**
     * Sets the value of the messages property.
     * 
     * @param value
     *     allowed object is
     *     {@link SendOperationType.Messages }
     *     
     */
    public void setMessages(SendOperationType.Messages value) {
        this.messages = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="send" type="{http://www.ccsds.org/schema/ServiceSchema}AnyTypeReference"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "send"
    })
    public static class Messages {

        @XmlElement(namespace = "http://www.ccsds.org/schema/ServiceSchema", required = true)
        protected AnyTypeReference send;

        /**
         * Gets the value of the send property.
         * 
         * @return
         *     possible object is
         *     {@link AnyTypeReference }
         *     
         */
        public AnyTypeReference getSend() {
            return send;
        }

        /**
         * Sets the value of the send property.
         * 
         * @param value
         *     allowed object is
         *     {@link AnyTypeReference }
         *     
         */
        public void setSend(AnyTypeReference value) {
            this.send = value;
        }

    }

}
