//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.15 at 03:22:23 PM CET 
//


package esa.mo.xsd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Element represents a Service specification inside an Area. May also optionally include data type and error definitions.
 * 
 * <p>Java class for ServiceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ServiceType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.ccsds.org/schema/ServiceSchema}DocumentationBaseType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="capabilitySet" type="{http://www.ccsds.org/schema/ServiceSchema}CapabilitySetType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="dataTypes" type="{http://www.ccsds.org/schema/ServiceSchema}DataTypeList" minOccurs="0"/&gt;
 *         &lt;element name="errors" type="{http://www.ccsds.org/schema/ServiceSchema}ErrorDefinitionList" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" /&gt;
 *       &lt;attribute name="number" use="required" type="{http://www.ccsds.org/schema/ServiceSchema}ServiceNumber" /&gt;
 *       &lt;attribute name="comment" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServiceType", namespace = "http://www.ccsds.org/schema/ServiceSchema", propOrder = {
    "capabilitySet",
    "dataTypes",
    "errors"
})
@XmlSeeAlso({
    ExtendedServiceType.class
})
public class ServiceType
    extends DocumentationBaseType
{

    @XmlElement(namespace = "http://www.ccsds.org/schema/ServiceSchema")
    protected List<CapabilitySetType> capabilitySet;
    @XmlElement(namespace = "http://www.ccsds.org/schema/ServiceSchema")
    protected DataTypeList dataTypes;
    @XmlElement(namespace = "http://www.ccsds.org/schema/ServiceSchema")
    protected ErrorDefinitionList errors;
    @XmlAttribute(name = "name", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String name;
    @XmlAttribute(name = "number", required = true)
    protected int number;
    @XmlAttribute(name = "comment")
    protected String comment;

    /**
     * Gets the value of the capabilitySet property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the capabilitySet property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCapabilitySet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CapabilitySetType }
     * 
     * 
     */
    public List<CapabilitySetType> getCapabilitySet() {
        if (capabilitySet == null) {
            capabilitySet = new ArrayList<CapabilitySetType>();
        }
        return this.capabilitySet;
    }

    /**
     * Gets the value of the dataTypes property.
     * 
     * @return
     *     possible object is
     *     {@link DataTypeList }
     *     
     */
    public DataTypeList getDataTypes() {
        return dataTypes;
    }

    /**
     * Sets the value of the dataTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataTypeList }
     *     
     */
    public void setDataTypes(DataTypeList value) {
        this.dataTypes = value;
    }

    /**
     * Gets the value of the errors property.
     * 
     * @return
     *     possible object is
     *     {@link ErrorDefinitionList }
     *     
     */
    public ErrorDefinitionList getErrors() {
        return errors;
    }

    /**
     * Sets the value of the errors property.
     * 
     * @param value
     *     allowed object is
     *     {@link ErrorDefinitionList }
     *     
     */
    public void setErrors(ErrorDefinitionList value) {
        this.errors = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the number property.
     * 
     */
    public int getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     * 
     */
    public void setNumber(int value) {
        this.number = value;
    }

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComment(String value) {
        this.comment = value;
    }

}
