//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.15 at 03:22:23 PM CET 
//


package esa.mo.xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SupportedFeatures complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SupportedFeatures"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.ccsds.org/schema/ServiceSchema}DocumentationBaseType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="objects" type="{http://www.ccsds.org/schema/COMSchema}ModelObjectTypeList" minOccurs="0"/&gt;
 *         &lt;element name="events" type="{http://www.ccsds.org/schema/COMSchema}ModelEventTypeList" minOccurs="0"/&gt;
 *         &lt;element name="archiveUsage" type="{http://www.ccsds.org/schema/COMSchema}CommentType" minOccurs="0"/&gt;
 *         &lt;element name="activityUsage" type="{http://www.ccsds.org/schema/COMSchema}CommentType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SupportedFeatures", namespace = "http://www.ccsds.org/schema/COMSchema", propOrder = {
    "objects",
    "events",
    "archiveUsage",
    "activityUsage"
})
public class SupportedFeatures
    extends DocumentationBaseType
{

    @XmlElement(namespace = "http://www.ccsds.org/schema/COMSchema")
    protected ModelObjectTypeList objects;
    @XmlElement(namespace = "http://www.ccsds.org/schema/COMSchema")
    protected ModelEventTypeList events;
    @XmlElement(namespace = "http://www.ccsds.org/schema/COMSchema")
    protected CommentType archiveUsage;
    @XmlElement(namespace = "http://www.ccsds.org/schema/COMSchema")
    protected CommentType activityUsage;

    /**
     * Gets the value of the objects property.
     * 
     * @return
     *     possible object is
     *     {@link ModelObjectTypeList }
     *     
     */
    public ModelObjectTypeList getObjects() {
        return objects;
    }

    /**
     * Sets the value of the objects property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModelObjectTypeList }
     *     
     */
    public void setObjects(ModelObjectTypeList value) {
        this.objects = value;
    }

    /**
     * Gets the value of the events property.
     * 
     * @return
     *     possible object is
     *     {@link ModelEventTypeList }
     *     
     */
    public ModelEventTypeList getEvents() {
        return events;
    }

    /**
     * Sets the value of the events property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModelEventTypeList }
     *     
     */
    public void setEvents(ModelEventTypeList value) {
        this.events = value;
    }

    /**
     * Gets the value of the archiveUsage property.
     * 
     * @return
     *     possible object is
     *     {@link CommentType }
     *     
     */
    public CommentType getArchiveUsage() {
        return archiveUsage;
    }

    /**
     * Sets the value of the archiveUsage property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommentType }
     *     
     */
    public void setArchiveUsage(CommentType value) {
        this.archiveUsage = value;
    }

    /**
     * Gets the value of the activityUsage property.
     * 
     * @return
     *     possible object is
     *     {@link CommentType }
     *     
     */
    public CommentType getActivityUsage() {
        return activityUsage;
    }

    /**
     * Sets the value of the activityUsage property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommentType }
     *     
     */
    public void setActivityUsage(CommentType value) {
        this.activityUsage = value;
    }

}
