package org.ccsds.moims.mo.com.event;

/**
 * Helper class for Event service.
 */
public class EventServiceInfo extends org.ccsds.moims.mo.com.COMService {

    /**
     * Service number literal.
     */
    public static final int _EVENT_SERVICE_NUMBER = 1;

    /**
     * Service number instance.
     */
    public static final org.ccsds.moims.mo.mal.structures.UShort EVENT_SERVICE_NUMBER = new org.ccsds.moims.mo.mal.structures.UShort(_EVENT_SERVICE_NUMBER);

    /**
     * Service name constant.
     */
    public static final org.ccsds.moims.mo.mal.structures.Identifier EVENT_SERVICE_NAME = new org.ccsds.moims.mo.mal.structures.Identifier("Event");

    /**
     * The service key of this service.
     */
    private static final org.ccsds.moims.mo.mal.ServiceKey SERVICE_KEY = new org.ccsds.moims.mo.mal.ServiceKey(
            2, 1, EVENT_SERVICE_NUMBER);

    /**
     * Operation number literal for operation MONITOREVENT.
     */
    public static final int _MONITOREVENT_OP_NUMBER = 1;

    /**
     * Operation number instance for operation MONITOREVENT.
     */
    private static final org.ccsds.moims.mo.mal.structures.UShort MONITOREVENT_OP_NUMBER = new org.ccsds.moims.mo.mal.structures.UShort(_MONITOREVENT_OP_NUMBER);

    /**
     * Operation instance for operation MONITOREVENT.
     */
    public static final org.ccsds.moims.mo.mal.MALPubSubOperation MONITOREVENT_OP = new org.ccsds.moims.mo.mal.MALPubSubOperation(SERVICE_KEY, 
            MONITOREVENT_OP_NUMBER, 
            new org.ccsds.moims.mo.mal.structures.Identifier("monitorEvent"), 
            new org.ccsds.moims.mo.mal.structures.UShort(1), 
            new org.ccsds.moims.mo.mal.OperationField[] {
                new org.ccsds.moims.mo.mal.OperationField("eventLinks", true, org.ccsds.moims.mo.com.structures.ObjectDetails.SHORT_FORM, "The MAL::EntityKey.firstSubKey shall contain the event object number as a base 10 string. For example, for an object number of '14' the key value would be '14' with no padding.\nThe MAL::EntityKey.secondSubKey shall contain the area, service, and version ObjectType fields as a MAL::Long populated as (in hex) 0xAAAASSSSVVXXXXXX where AAAA is the area (16 bits), SSSS is the service (16 bits), VV is the version (8 bits), and XXXXXX is unused and set to zero (24 bits). For example, for an area of '1', and a service of '2', and a version of '3' the field would contain (in hex) 0x0001000203000000.\nThe MAL::EntityKey.thirdSubKey shall contain the event object instance identifier.\nThe MAL::EntityKey.fourthSubKey shall contain the area, service, version and number fields of the event source ObjectType using same methodology as given for the second sub key but replacing the XXXXXX part with the number field.\nThe related and source links of the event shall populate the ObjectDetails part of the publish/notify message.\nThe body of the event shall populate the final part of the publish/notify message.\nThe timestamp of the Event shall be taken from the publish message.\nAn event in one domain may be generated by something in another domain therefore the domain of the event shall not be required to be the same domain as the source of the event."),
                new org.ccsds.moims.mo.mal.OperationField("eventBody", true, null, null)}, 
            "The monitorEvent operation allows a consumer to subscribe for events.");

    /**
     * Key names instance for MONITOREVENT operation of pubsub interaction pattern.
     */
    private static final org.ccsds.moims.mo.mal.structures.Identifier [] _MONITOREVENT_OP_KEY_NAMES = {};

    /**
     * Key names instance for MONITOREVENT operation of pubsub interaction pattern.
     */
    private static final org.ccsds.moims.mo.mal.structures.IdentifierList MONITOREVENT_OP_KEY_NAMES = new org.ccsds.moims.mo.mal.structures.IdentifierList(new java.util.ArrayList<>(java.util.Arrays.asList(_MONITOREVENT_OP_KEY_NAMES)));

    /**
     * Area elements.
     */
    public static final org.ccsds.moims.mo.mal.structures.Element[] EVENT_SERVICE_ELEMENTS = {};

    /**
     * The set of operations for this service.
     */
    public static final org.ccsds.moims.mo.mal.MALOperation[] OPERATIONS = new org.ccsds.moims.mo.mal.MALOperation[]{MONITOREVENT_OP};

    /**
     * Creates an instance of the Event ServiceInfo.
     * 
     */
    public EventServiceInfo() {
        super(SERVICE_KEY, EVENT_SERVICE_NAME, EVENT_SERVICE_ELEMENTS, OPERATIONS);
    }

    @Override
    public org.ccsds.moims.mo.mal.MALArea getArea() {
        return org.ccsds.moims.mo.com.COMHelper.COM_AREA;
    }

    @Override
    public org.ccsds.moims.mo.mal.MOErrorException generateMOError(int errorNumber,
            Object extraInfo) {
        switch (errorNumber) {
            case 70000:
                return new org.ccsds.moims.mo.com.InvalidException(extraInfo);
            case 70001:
                return new org.ccsds.moims.mo.com.DuplicateException(extraInfo);
        }
        return null;
    }

}
