package org.ccsds.moims.mo.com.event;

import java.util.ArrayList;
import java.util.Arrays;
import org.ccsds.moims.mo.com.COMHelper;
import org.ccsds.moims.mo.com.COMService;
import org.ccsds.moims.mo.com.structures.ObjectDetails;
import org.ccsds.moims.mo.mal.MALArea;
import org.ccsds.moims.mo.mal.MALHelper;
import org.ccsds.moims.mo.mal.MALOperation;
import org.ccsds.moims.mo.mal.MALPubSubOperation;
import org.ccsds.moims.mo.mal.MOErrorException;
import org.ccsds.moims.mo.mal.OperationField;
import org.ccsds.moims.mo.mal.ServiceKey;
import org.ccsds.moims.mo.mal.structures.Element;
import org.ccsds.moims.mo.mal.structures.Identifier;
import org.ccsds.moims.mo.mal.structures.IdentifierList;
import org.ccsds.moims.mo.mal.structures.UShort;

/**
 * Helper class for Event service.
 */
public class EventServiceInfo extends COMService {

    /**
     * Service number literal.
     */
    public static final int _EVENT_SERVICE_NUMBER = 1;

    /**
     * Service number instance.
     */
    public static final UShort EVENT_SERVICE_NUMBER = new UShort(_EVENT_SERVICE_NUMBER);

    /**
     * Service name constant.
     */
    public static final Identifier EVENT_SERVICE_NAME = new Identifier("Event");

    /**
     * The service key of this service.
     */
    private static final ServiceKey SERVICE_KEY = new ServiceKey(
            2, 1, EVENT_SERVICE_NUMBER);

    /**
     * Operation number literal for operation MONITOREVENT.
     */
    public static final int _MONITOREVENT_OP_NUMBER = 1;

    /**
     * Operation number instance for operation MONITOREVENT.
     */
    private static final UShort MONITOREVENT_OP_NUMBER = new UShort(_MONITOREVENT_OP_NUMBER);

    /**
     * Operation instance for operation MONITOREVENT.
     */
    public static final MALPubSubOperation MONITOREVENT_OP = new MALPubSubOperation(SERVICE_KEY, 
            MONITOREVENT_OP_NUMBER, 
            new Identifier("monitorEvent"), 
            new UShort(1), 
            new OperationField[] {
                new OperationField("eventLinks", true, ObjectDetails.SHORT_FORM, "The MAL::EntityKey.firstSubKey shall contain the event object number as a base 10 string. For example, for an object number of '14' the key value would be '14' with no padding.\nThe MAL::EntityKey.secondSubKey shall contain the area, service, and version ObjectType fields as a MAL::Long populated as (in hex) 0xAAAASSSSVVXXXXXX where AAAA is the area (16 bits), SSSS is the service (16 bits), VV is the version (8 bits), and XXXXXX is unused and set to zero (24 bits). For example, for an area of '1', and a service of '2', and a version of '3' the field would contain (in hex) 0x0001000203000000.\nThe MAL::EntityKey.thirdSubKey shall contain the event object instance identifier.\nThe MAL::EntityKey.fourthSubKey shall contain the area, service, version and number fields of the event source ObjectType using same methodology as given for the second sub key but replacing the XXXXXX part with the number field.\nThe related and source links of the event shall populate the ObjectDetails part of the publish/notify message.\nThe body of the event shall populate the final part of the publish/notify message.\nThe timestamp of the Event shall be taken from the publish message.\nAn event in one domain may be generated by something in another domain therefore the domain of the event shall not be required to be the same domain as the source of the event."),
                new OperationField("eventBody", true, null, null)}, 
            "The monitorEvent operation allows a consumer to subscribe for events.");

    /**
     * Key names instance for MONITOREVENT operation of pubsub interaction pattern.
     */
    private static final Identifier [] _MONITOREVENT_OP_KEY_NAMES = {};

    /**
     * Key names instance for MONITOREVENT operation of pubsub interaction pattern.
     */
    private static final IdentifierList MONITOREVENT_OP_KEY_NAMES = new IdentifierList(new ArrayList<>(Arrays.asList(_MONITOREVENT_OP_KEY_NAMES)));

    /**
     * Area elements.
     */
    public static final Element[] EVENT_SERVICE_ELEMENTS = {};

    /**
     * The set of operations for this service.
     */
    public static final MALOperation[] OPERATIONS = new MALOperation[]{MONITOREVENT_OP};

    /**
     * Creates an instance of the Event ServiceInfo.
     * 
     */
    public EventServiceInfo() {
        super(SERVICE_KEY, EVENT_SERVICE_NAME, EVENT_SERVICE_ELEMENTS, OPERATIONS);
    }

    @Override
    public MALArea getArea() {
        return COMHelper.COM_AREA;
    }

    @Override
    public MOErrorException generateMOError(int operationNumber,
            int errorNumber,
            Object extraInfo) {
        MOErrorException areaError = COMHelper.generateMOError(errorNumber, extraInfo);
        return (areaError != null) ? areaError : MALHelper.generateMOError(errorNumber, extraInfo);
    }

}
