name: Testbeds
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Run the Maven install
        run: mvn --batch-mode --update-snapshots -P ESA -DskipTests install
      - name: Cache Maven local repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

  testbed-mal:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Restore Maven local repository from cache
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
      - name: Run the Testbed for MAL
        run: mvn --batch-mode --update-snapshots -P ESA test
        working-directory: testbeds/testbed-mal
      - name: Upload report for MAL testbed
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: testbed-mal-report
          path: testbeds/testbed-mal/target/surefire-reports/

  testbed-com:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Restore Maven local repository from cache
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
      - name: Run the Testbed for COM
        run: mvn --batch-mode --update-snapshots -P ESA test
        working-directory: testbeds/testbed-com
      - name: Upload report for COM testbed
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: testbed-com-report
          path: testbeds/testbed-com/target/surefire-reports/
